name: CI
run-name: ${{ github.actor }} is CI on going
on:
  push:
    branches:
      - 'feature**'
      - 'fix**'
      - 'bug**'

  workflow_dispatch:

env:
  POSTGRESQL_VERSION: 13.1
  POSTGRESQL_DB: api-database
  POSTGRESQL_USER: postgres
  POSTGRESQL_PASSWORD: password
  NODE_VERSION: 20
  DOCKER_HUB_USERNAME: renatofagalde
  # AWS & Elastic Bean Stalk
  AWS_REGION: us-east-1
  EB_ENVIRONMENT_NAME: 'apinode-env'
  EB_APPLICATION_NAME: 'api node'
  EB_DEPLOYMENT_PACKAGE: ./src/elasticbeanstalk/docker-compose.yml


jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13.1
        env:
          POSTGRES_DB: ${{ env.POSTGRESQL_DB }}
          POSTGRES_USER: ${{ env.POSTGRESQL_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRESQL_PASSWORD }}
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: npm install -g bats
      - run: bats -v

      - name: Build Number
        id: build-number
        run: echo "::set-output name=BUILD_NUMBER::$(date '+%-d.%-m.%Y.%-H.%-M.%-S')"

      - name: Docker Login
        uses: docker/login-action@f3364599c6aa293cdc2b8391b1b56d0c30e45c8a
        run: |
          docker login -u ${{env.DOCKER_HUB_USERNAME}} -p $DOCKER_PASSWORD
      - name: Build and Push to Dockerhub
        run:  docker build . --file Dockerfile --tag renatofagalde/api-nodejs-cicd:${{steps.build-number.outputs.BUILD_NUMBER}}